import type { AISANode } from '@/types/aisa'

// ═══════════════════════════════════════════════════════════════════════
// G3 — ETHICAL AI ASSESSMENT
// ═══════════════════════════════════════════════════════════════════════

// ─── SA1: Bias and Fairness Assessment ────────────────────────────────

const EG_BIAS_IDENTIFICATION: AISANode = {
  id: 'p2-g3-sa1-t1-eg',
  type: 'execution-guide',
  level: 5,
  title: 'EG: Identifying Potential Sources of Bias',
  description: 'Systematically identify all potential sources of bias in the AI system — from training data, model design, deployment context, and feedback loops — before model development begins.',
  purpose: 'Surface bias risks before model training so that data curation, feature selection, and evaluation decisions are made with awareness of bias potential.',
  why_it_matters: 'Bias in AI systems reflects and amplifies bias in historical data. A model trained on historical decisions that discriminated against protected groups will predict discriminatory outcomes. Identifying bias sources before training is the only point at which bias can be prevented rather than mitigated after the fact.',
  methods: [
    '1. Historical data bias: review the training data for representation gaps. Are all demographic groups (age, gender, ethnicity, disability) proportionally represented? Are any groups systematically underrepresented?',
    '2. Label bias: how were training labels created? Were they generated by human annotators who may carry implicit biases? Were they derived from historical decisions that reflected systemic discrimination?',
    '3. Proxy discrimination: identify features that are not protected characteristics themselves but are strongly correlated with protected characteristics (e.g., postcode as a proxy for ethnicity).',
    '4. Measurement bias: are any features measured differently for different demographic groups (e.g., a test that was validated on one population being applied to another)?',
    '5. Feedback loop bias: will the AI system\'s outputs influence future training data? If the system makes decisions that affect who enters the training set for future iterations, it may amplify its own biases over time.',
    '6. Deployment context bias: are there demographic groups that will be differentially affected by errors in the system — even if the overall accuracy is high?',
    '7. Document each identified bias source with: type, mechanism, affected groups, and severity assessment (1–3: Low/Medium/High).',
  ],
  tools: ['Bias identification template', 'Protected characteristics reference list', 'Training data demographic analysis'],
  outputs: ['Bias source register: type, mechanism, affected groups, and severity for each identified bias risk'],
  exit_criteria: ['All six bias source categories examined; bias register produced; Ethics team and DPO reviewed'],
}

const T_BIAS_IDENTIFICATION: AISANode = {
  id: 'p2-g3-sa1-t1',
  type: 'task',
  level: 4,
  title: 'Identify Bias Sources',
  description: 'Systematically identify all bias sources across training data, labels, proxy features, measurement, feedback loops, and deployment context.',
  purpose: 'Surface bias risks before model training so mitigation can be built into the design.',
  inputs: ['Data landscape assessment from D6', 'Decision Analysis from D7', 'Protected characteristics reference list', 'Bias identification template'],
  methods: ['Six-category bias source review', 'Demographic representation analysis', 'Proxy feature identification', 'Feedback loop mapping'],
  tools: ['Bias identification template'],
  outputs: ['Bias source register with severity assessments'],
  children: [EG_BIAS_IDENTIFICATION],
}

const EG_FAIRNESS_METRICS: AISANode = {
  id: 'p2-g3-sa1-t2-eg',
  type: 'execution-guide',
  level: 5,
  title: 'EG: Defining Fairness Metrics and Evaluation Requirements',
  description: 'Select the appropriate fairness metrics for the use case and define how the model will be evaluated for differential performance across demographic groups.',
  purpose: 'Establish measurable fairness standards before model training so evaluation is objective rather than post-hoc rationalisation.',
  why_it_matters: 'Different fairness definitions are mathematically incompatible — you cannot simultaneously satisfy demographic parity, equalised odds, and individual fairness in most real-world settings. Choosing the appropriate definition for the use case before training ensures the model is optimised for the right fairness criterion.',
  methods: [
    '1. Select the primary fairness metric appropriate to the use case:',
    '   — Demographic parity: equal positive prediction rates across groups. Appropriate when historical decisions were biased and historical patterns should not be perpetuated.',
    '   — Equalised odds: equal true positive AND false positive rates across groups. Appropriate when errors must be equally distributed.',
    '   — Individual fairness: similar individuals receive similar predictions. Appropriate when individual characteristics dominate.',
    '   — Calibration: predicted probabilities accurately reflect actual rates across groups.',
    '2. For each protected characteristic in scope, define: the subgroup segmentation (how the population is divided), the fairness metric, and the maximum acceptable disparity (e.g., no group may have a false negative rate more than 10% higher than the best-performing group).',
    '3. Define the evaluation methodology: how will demographic data be obtained for evaluation? (Note: collecting demographic data for evaluation may require its own lawful basis.)',
    '4. Include fairness metrics as a required component of the model acceptance criteria from D9.',
  ],
  tools: ['Fairness metrics selection guide', 'Subgroup evaluation template'],
  outputs: ['Fairness metrics specification: primary metric, subgroup definitions, disparity tolerances, and evaluation methodology'],
  exit_criteria: ['Primary fairness metric selected and justified; subgroup evaluation specification confirmed; integrated into D9 acceptance criteria'],
}

const T_FAIRNESS_METRICS: AISANode = {
  id: 'p2-g3-sa1-t2',
  type: 'task',
  level: 4,
  title: 'Define Fairness Metrics and Evaluation Requirements',
  description: 'Select the appropriate fairness metric and define subgroup evaluation requirements.',
  purpose: 'Establish measurable fairness standards before training so evaluation is objective.',
  inputs: ['Bias source register from T_BIAS_IDENTIFICATION', 'Use case description', 'Protected characteristics in scope', 'Fairness metrics selection guide'],
  methods: ['Fairness metric selection and justification', 'Subgroup segmentation definition', 'Disparity tolerance setting', 'Integration with D9 acceptance criteria'],
  tools: ['Fairness metrics selection guide'],
  outputs: ['Fairness metrics specification integrated into acceptance criteria'],
  children: [EG_FAIRNESS_METRICS],
}

const SA1_BIAS_FAIRNESS: AISANode = {
  id: 'p2-g3-sa1',
  type: 'sub-activity',
  level: 3,
  title: 'Bias and Fairness Assessment',
  description: 'Identify all sources of bias in the AI system design and establish measurable fairness metrics and evaluation requirements as mandatory model acceptance criteria.',
  purpose: 'Ensure bias is identified before training and fairness standards are established before acceptance testing.',
  why_it_matters: 'Bias and fairness failures in AI systems cause real harm to real people — particularly in high-stakes domains like employment, credit, and healthcare. The ethical obligation to prevent these harms, the legal obligation under EU equality law and the EU AI Act, and the reputational risk of public failure all converge on the same requirement: assess bias rigorously before deploying.',
  inputs: ['Data landscape assessment from D6', 'Use case description', 'Protected characteristics applicable to the deployment context'],
  questions: ['Where might training data, labels, or proxy features introduce bias?', 'Which groups might be differentially harmed by errors?', 'Which fairness metric is appropriate for this use case?', 'What disparity tolerance is acceptable?'],
  methods: ['Six-category bias source identification', 'Fairness metric selection and justification', 'Subgroup evaluation specification'],
  tools: ['Bias identification template', 'Fairness metrics selection guide'],
  governance_considerations: 'The EU AI Act (Art. 9, Art. 10) requires High Risk AI systems to implement data governance practices that address bias. Fairness metrics must be included in the technical documentation (Art. 11) and validated before conformity assessment (Art. 43).',
  outputs: ['Bias source register with severity assessments', 'Fairness metrics specification integrated into D9 acceptance criteria'],
  deliverables: ['Bias and Fairness Assessment (input to Ethical AI Assessment Report)'],
  exit_criteria: ['Bias register complete with severity assessments; fairness metrics specified and integrated into acceptance criteria; Ethics team, DPO, and Legal reviewed'],
  children: [T_BIAS_IDENTIFICATION, T_FAIRNESS_METRICS],
}

// ─── SA2: Ethical Risk Assessment ─────────────────────────────────────

const EG_ETHICAL_RISK: AISANode = {
  id: 'p2-g3-sa2-t1-eg',
  type: 'execution-guide',
  level: 5,
  title: 'EG: Conducting the Ethical Risk Assessment',
  description: 'Apply a structured ethical risk framework to identify how the AI system may cause harm to individuals, communities, or society — beyond the technical risks assessed elsewhere.',
  purpose: 'Surface ethical risks that are not captured by compliance frameworks but that could cause harm or erode trust in the AI system.',
  why_it_matters: 'Legal compliance is necessary but not sufficient for ethical AI. Systems that comply with GDPR and the EU AI Act can still cause harm through unintended consequences, power asymmetries, or erosion of human autonomy. Ethical risk assessment is the mechanism that catches what compliance frameworks miss.',
  methods: [
    '1. Apply the IEEE Ethically Aligned Design framework dimensions: human wellbeing, data agency, accountability, transparency, algorithmic bias, privacy, and security.',
    '2. For each dimension, ask: "In what scenario could this AI system cause harm through this dimension?" Document specific scenarios, not abstract risks.',
    '3. Assess the impact of the identified ethical risks on: individuals directly affected, communities that share characteristics with affected individuals, and wider society.',
    '4. Assess likelihood: how probable is each ethical risk scenario given the system design and deployment context?',
    '5. Prioritise risks: severity × likelihood = priority score. Focus mitigation design on high-priority ethical risks.',
    '6. For each high-priority ethical risk, define a specific mitigation: a design change, an oversight mechanism, a transparency measure, or a scope limitation.',
  ],
  tools: ['Ethical risk assessment template', 'IEEE Ethically Aligned Design reference'],
  outputs: ['Ethical risk register: scenario, dimension, impact, likelihood, priority, and mitigation for each identified risk'],
  exit_criteria: ['All IEEE dimensions assessed; ethical risk register produced with priority scores; high-priority risks have specific mitigations; Ethics committee reviewed'],
}

const T_ETHICAL_RISK: AISANode = {
  id: 'p2-g3-sa2-t1',
  type: 'task',
  level: 4,
  title: 'Ethical Risk Assessment',
  description: 'Apply IEEE Ethically Aligned Design dimensions to identify ethical risks and define mitigations for high-priority items.',
  purpose: 'Identify harms that legal compliance frameworks do not capture.',
  inputs: ['Bias source register from SA1', 'Decision Analysis from D7', 'System scope from D11', 'Ethical risk assessment template', 'Ethics committee contact'],
  methods: ['IEEE dimension-based risk scenario generation', 'Impact and likelihood assessment', 'Priority scoring', 'Mitigation design for high-priority risks'],
  tools: ['Ethical risk assessment template', 'IEEE Ethically Aligned Design reference'],
  outputs: ['Ethical risk register with mitigations for high-priority risks'],
  children: [EG_ETHICAL_RISK],
}

const SA2_ETHICAL_RISK: AISANode = {
  id: 'p2-g3-sa2',
  type: 'sub-activity',
  level: 3,
  title: 'Ethical Risk Assessment',
  description: 'Apply the IEEE Ethically Aligned Design framework to identify, prioritise, and mitigate ethical risks across human wellbeing, data agency, accountability, transparency, bias, privacy, and security dimensions.',
  purpose: 'Identify and mitigate harms that legal frameworks do not capture but that could cause real damage to individuals, communities, or the organisation\'s trust.',
  why_it_matters: 'Ethical AI is not just good practice — it is increasingly a commercial and regulatory expectation. Systems that are technically compliant but ethically harmful create reputational, legal, and operational risk. The EU AI Act and the OECD AI Principles expect providers to go beyond minimum legal compliance.',
  inputs: ['Bias source register from SA1', 'Decision Analysis from D7', 'System scope from D11'],
  questions: ['How could this AI system harm individuals or communities beyond what compliance frameworks require?', 'What ethical scenarios have we not considered?', 'What is the highest-priority ethical risk, and how do we mitigate it?'],
  methods: ['IEEE dimension-based assessment', 'Scenario generation', 'Priority scoring', 'Mitigation design'],
  tools: ['Ethical risk assessment template'],
  outputs: ['Ethical risk register with high-priority mitigations'],
  deliverables: ['Ethical Risk Register (input to Ethical AI Assessment Report)'],
  exit_criteria: ['All dimensions assessed; register produced with priority scores and mitigations; Ethics committee reviewed'],
  children: [T_ETHICAL_RISK],
}

// ─── SA3: Transparency and Explainability Requirements ────────────────

const EG_EXPLAINABILITY: AISANode = {
  id: 'p2-g3-sa3-t1-eg',
  type: 'execution-guide',
  level: 5,
  title: 'EG: Defining Transparency and Explainability Requirements',
  description: 'Define what the AI system must communicate about its operation, decisions, and limitations to different audiences — operators, users, affected individuals, and regulators.',
  purpose: 'Establish explainability requirements as architecture inputs before model selection, ensuring that interpretability constraints inform model choice rather than being retrofitted after a non-interpretable model is trained.',
  why_it_matters: 'Choosing a highly accurate but non-interpretable model (e.g., a deep neural network) and then attempting to retrofit explainability is a common and costly mistake. Explainability requirements established in Phase 2 constrain model selection in Phase 3 to architectures that can meet them — either inherently interpretable models or post-hoc explanation methods that are adequate for the use case.',
  methods: [
    '1. Identify the audiences who need explanations: (a) Operators — what do they need to understand to oversee the system?; (b) End users — what do they need to know about how the system affects them?; (c) Affected individuals — what must be disclosed when the system makes or supports a decision about them (Art. 13/14 GDPR transparency, EU AI Act Art. 13)?; (d) Regulators — what documentation is required for audit and conformity assessment?',
    '2. For each audience, define: what must be explained, at what level of detail, in what language and format, and with what frequency.',
    '3. Define the explanation depth required: (a) Feature importance (which inputs influenced the prediction); (b) Counterfactual (what would change the outcome); (c) Rule extraction (what rule-based representation captures model behaviour); (d) Example-based (which training examples are similar to this prediction).',
    '4. Assess whether the required explanation depth is compatible with the planned model type. If not, the model type must change or the explanation depth must be negotiated with the Business Owner and DPO.',
    '5. Document explainability requirements as Phase 3 model architecture constraints.',
  ],
  tools: ['Explainability requirements template', 'Explanation method comparison guide (SHAP, LIME, counterfactuals, rule extraction)'],
  outputs: ['Explainability requirements specification: per audience — what, depth, format, frequency; as Phase 3 model architecture constraints'],
  exit_criteria: ['Requirements defined for all four audiences; explanation depth specified; compatibility with planned model type assessed; DPO and Business Owner confirmed'],
}

const T_EXPLAINABILITY: AISANode = {
  id: 'p2-g3-sa3-t1',
  type: 'task',
  level: 4,
  title: 'Define Transparency and Explainability Requirements',
  description: 'Specify explainability requirements for each audience as constraints on Phase 3 model architecture.',
  purpose: 'Ensure explainability requirements constrain model selection before a non-interpretable model is chosen.',
  inputs: ['Ethical risk register from SA2', 'GDPR transparency obligations from G2', 'EU AI Act Art. 13 obligations from G1', 'Explainability requirements template'],
  methods: ['Four-audience explainability specification', 'Explanation depth assessment', 'Model type compatibility check', 'Architecture constraint documentation'],
  tools: ['Explainability requirements template', 'Explanation method guide'],
  outputs: ['Explainability requirements specification as Phase 3 architecture constraints'],
  children: [EG_EXPLAINABILITY],
}

const SA3_EXPLAINABILITY: AISANode = {
  id: 'p2-g3-sa3',
  type: 'sub-activity',
  level: 3,
  title: 'Transparency and Explainability Requirements',
  description: 'Define what the AI system must communicate about its decisions to operators, users, affected individuals, and regulators, and specify these as architecture constraints for Phase 3.',
  purpose: 'Establish explainability requirements before model selection so that interpretability constrains model choice from the outset.',
  why_it_matters: 'Transparency is both a legal requirement (GDPR Art. 13/14, EU AI Act Art. 13) and an ethical imperative. AI systems that cannot explain their decisions to those affected by them violate individual rights and erode public trust. Defining explainability before model selection ensures it is possible.',
  inputs: ['Ethical risk register from SA2', 'GDPR obligations from G2', 'EU AI Act obligations from G1', 'Decision Analysis from D7'],
  questions: ['Who needs to understand this system\'s decisions and why?', 'What level of explanation is required for each audience?', 'Does the planned model type support the required explanation depth?'],
  methods: ['Audience identification', 'Explanation depth specification', 'Model type compatibility assessment'],
  tools: ['Explainability requirements template'],
  outputs: ['Explainability requirements specification'],
  deliverables: ['Explainability Requirements (Phase 3 architecture constraint)'],
  exit_criteria: ['Requirements defined for all four audiences; explanation depth confirmed; model type compatibility assessed; DPO confirmed legal sufficiency'],
  children: [T_EXPLAINABILITY],
}

// ═══════════════════════════════════════════════════════════════════════
// G3 — ACTIVITY NODE
// ═══════════════════════════════════════════════════════════════════════

export const G3: AISANode = {
  id: 'p2-g3',
  type: 'activity',
  level: 2,
  title: 'G3 — Ethical AI Assessment',
  description: 'Conduct a comprehensive ethical assessment of the AI initiative covering bias identification, fairness metric specification, ethical risk assessment, and transparency/explainability requirements — producing the Ethical AI Assessment Report and explainability architecture constraints.',
  purpose: 'Ensure the AI system is designed to be fair, transparent, and free from unacceptable ethical risks before architecture decisions make these properties hard to achieve.',
  why_it_matters: 'Ethical failures in AI are not abstract — they are systems that refuse loan applications from specific postcodes, reject resumes from candidates with non-Western names, or provide inferior medical triage to specific demographics. These harms are real, litigable, and reputationally catastrophic. G3 is where they are prevented.',
  principles_applied: ['Privacy and Ethics by Design', 'Human Accountability Cannot Be Delegated'],
  inputs: ['Data landscape assessment from D6', 'Decision Analysis from D7', 'EU AI Act compliance assessment from G1', 'GDPR assessment from G2', 'Ethics committee contact'],
  questions: [
    'Where are the bias risks in training data, labels, proxy features, and feedback loops?',
    'Which fairness metric is appropriate, and what disparity tolerance is acceptable?',
    'What are the ethical risks beyond legal compliance?',
    'What explainability is required by whom, and can the planned model architecture deliver it?',
  ],
  activities: [
    'Identify bias sources across all six categories and assess severity',
    'Select fairness metrics and define subgroup evaluation requirements',
    'Conduct ethical risk assessment using IEEE Ethically Aligned Design framework',
    'Define transparency and explainability requirements for all four audiences as architecture constraints',
  ],
  methods: ['Six-category bias source analysis', 'Fairness metric selection', 'IEEE dimension-based ethical risk assessment', 'Explainability requirements specification'],
  tools: ['Bias identification template', 'Fairness metrics selection guide', 'Ethical risk assessment template', 'Explainability requirements template'],
  governance_considerations: 'Ethical AI Assessment outputs must be reviewed by the Ethics committee or equivalent body, the DPO, and Legal before Phase 3 begins. High-priority ethical risks must have defined mitigations that are embedded in Phase 3 architecture requirements.',
  ai_engineering_considerations: 'Bias mitigation and fairness constraints are data engineering and model training requirements. ML engineers must be briefed on the bias register and fairness specifications before feature engineering begins — not as post-training compliance checks. Explainability requirements constrain model architecture selection.',
  outputs: ['Bias source register with severity assessments', 'Fairness metrics specification integrated into acceptance criteria', 'Ethical risk register with mitigations', 'Explainability requirements as Phase 3 architecture constraints'],
  deliverables: ['Ethical AI Assessment Report (Phase 2 Deliverable)'],
  exit_criteria: [
    'Bias register complete and Ethics committee reviewed',
    'Fairness metrics integrated into D9 acceptance criteria',
    'Ethical risk register produced with mitigations for high-priority risks',
    'Explainability requirements specified and confirmed by DPO',
    'All outputs included in Phase 3 architecture brief',
  ],
  related_phases: ['phase-3', 'phase-4'],
  references: [
    { title: 'IEEE Ethically Aligned Design, 1st Edition', type: 'framework' },
    { title: 'Fairness and Machine Learning — Barocas, Hardt, Narayanan', type: 'book' },
    { title: 'EU AI Act Art. 10 — Data and data governance', type: 'standard' },
    { title: 'OECD Principles on AI', type: 'framework' },
  ],
  children: [SA1_BIAS_FAIRNESS, SA2_ETHICAL_RISK, SA3_EXPLAINABILITY],
}
