/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FrameworksThreeStructuralLawsRouteImport } from './routes/frameworks-three-structural-laws'
import { Route as FrameworksSkaidoRouteImport } from './routes/frameworks-skaido'
import { Route as FrameworksRouteImport } from './routes/frameworks'
import { Route as DeRouteImport } from './routes/de'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AisaV2RouteImport } from './routes/aisa-v2'
import { Route as AisaRouteImport } from './routes/aisa'
import { Route as AiAgentRouteImport } from './routes/ai-agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as InsightsIndexRouteImport } from './routes/insights/index'
import { Route as DeIndexRouteImport } from './routes/de/index'
import { Route as PortfolioKnowledgeArchitectureOperatingSystemRouteImport } from './routes/portfolio/knowledge-architecture-operating-system'
import { Route as PortfolioInsuranceClaimsIntelligencePlatformRouteImport } from './routes/portfolio/insurance-claims-intelligence-platform'
import { Route as PortfolioCareerIntelligenceOperatingSystemRouteImport } from './routes/portfolio/career-intelligence-operating-system'
import { Route as InsightsSlugRouteImport } from './routes/insights/$slug'
import { Route as DePublicationsRouteImport } from './routes/de/publications'
import { Route as DePortfolioRouteImport } from './routes/de/portfolio'
import { Route as DeInsightsRouteImport } from './routes/de/insights'
import { Route as DeFrameworksRouteImport } from './routes/de/frameworks'
import { Route as DeContactRouteImport } from './routes/de/contact'
import { Route as DeAiAgentRouteImport } from './routes/de/ai-agent'
import { Route as DeAboutRouteImport } from './routes/de/about'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DePortfolioIndexRouteImport } from './routes/de/portfolio/index'
import { Route as DePortfolioInsuranceClaimsIntelligencePlatformRouteImport } from './routes/de/portfolio/insurance-claims-intelligence-platform'
import { Route as DePortfolioCareerIntelligenceOperatingSystemRouteImport } from './routes/de/portfolio/career-intelligence-operating-system'

const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksThreeStructuralLawsRoute =
  FrameworksThreeStructuralLawsRouteImport.update({
    id: '/frameworks-three-structural-laws',
    path: '/frameworks-three-structural-laws',
    getParentRoute: () => rootRouteImport,
  } as any)
const FrameworksSkaidoRoute = FrameworksSkaidoRouteImport.update({
  id: '/frameworks-skaido',
  path: '/frameworks-skaido',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksRoute = FrameworksRouteImport.update({
  id: '/frameworks',
  path: '/frameworks',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRoute = DeRouteImport.update({
  id: '/de',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AisaV2Route = AisaV2RouteImport.update({
  id: '/aisa-v2',
  path: '/aisa-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const AisaRoute = AisaRouteImport.update({
  id: '/aisa',
  path: '/aisa',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentRoute = AiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const DeIndexRoute = DeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeRoute,
} as any)
const PortfolioKnowledgeArchitectureOperatingSystemRoute =
  PortfolioKnowledgeArchitectureOperatingSystemRouteImport.update({
    id: '/knowledge-architecture-operating-system',
    path: '/knowledge-architecture-operating-system',
    getParentRoute: () => PortfolioRoute,
  } as any)
const PortfolioInsuranceClaimsIntelligencePlatformRoute =
  PortfolioInsuranceClaimsIntelligencePlatformRouteImport.update({
    id: '/insurance-claims-intelligence-platform',
    path: '/insurance-claims-intelligence-platform',
    getParentRoute: () => PortfolioRoute,
  } as any)
const PortfolioCareerIntelligenceOperatingSystemRoute =
  PortfolioCareerIntelligenceOperatingSystemRouteImport.update({
    id: '/career-intelligence-operating-system',
    path: '/career-intelligence-operating-system',
    getParentRoute: () => PortfolioRoute,
  } as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const DePublicationsRoute = DePublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => DeRoute,
} as any)
const DePortfolioRoute = DePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DeRoute,
} as any)
const DeInsightsRoute = DeInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DeRoute,
} as any)
const DeFrameworksRoute = DeFrameworksRouteImport.update({
  id: '/frameworks',
  path: '/frameworks',
  getParentRoute: () => DeRoute,
} as any)
const DeContactRoute = DeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => DeRoute,
} as any)
const DeAiAgentRoute = DeAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => DeRoute,
} as any)
const DeAboutRoute = DeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DeRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DePortfolioIndexRoute = DePortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DePortfolioRoute,
} as any)
const DePortfolioInsuranceClaimsIntelligencePlatformRoute =
  DePortfolioInsuranceClaimsIntelligencePlatformRouteImport.update({
    id: '/insurance-claims-intelligence-platform',
    path: '/insurance-claims-intelligence-platform',
    getParentRoute: () => DePortfolioRoute,
  } as any)
const DePortfolioCareerIntelligenceOperatingSystemRoute =
  DePortfolioCareerIntelligenceOperatingSystemRouteImport.update({
    id: '/career-intelligence-operating-system',
    path: '/career-intelligence-operating-system',
    getParentRoute: () => DePortfolioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-agent': typeof AiAgentRoute
  '/aisa': typeof AisaRoute
  '/aisa-v2': typeof AisaV2Route
  '/contact': typeof ContactRoute
  '/de': typeof DeRouteWithChildren
  '/frameworks': typeof FrameworksRoute
  '/frameworks-skaido': typeof FrameworksSkaidoRoute
  '/frameworks-three-structural-laws': typeof FrameworksThreeStructuralLawsRoute
  '/insights': typeof InsightsRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/api/chat': typeof ApiChatRoute
  '/de/about': typeof DeAboutRoute
  '/de/ai-agent': typeof DeAiAgentRoute
  '/de/contact': typeof DeContactRoute
  '/de/frameworks': typeof DeFrameworksRoute
  '/de/insights': typeof DeInsightsRoute
  '/de/portfolio': typeof DePortfolioRouteWithChildren
  '/de/publications': typeof DePublicationsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/portfolio/career-intelligence-operating-system': typeof PortfolioCareerIntelligenceOperatingSystemRoute
  '/portfolio/insurance-claims-intelligence-platform': typeof PortfolioInsuranceClaimsIntelligencePlatformRoute
  '/portfolio/knowledge-architecture-operating-system': typeof PortfolioKnowledgeArchitectureOperatingSystemRoute
  '/de/': typeof DeIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/de/portfolio/career-intelligence-operating-system': typeof DePortfolioCareerIntelligenceOperatingSystemRoute
  '/de/portfolio/insurance-claims-intelligence-platform': typeof DePortfolioInsuranceClaimsIntelligencePlatformRoute
  '/de/portfolio/': typeof DePortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-agent': typeof AiAgentRoute
  '/aisa': typeof AisaRoute
  '/aisa-v2': typeof AisaV2Route
  '/contact': typeof ContactRoute
  '/frameworks': typeof FrameworksRoute
  '/frameworks-skaido': typeof FrameworksSkaidoRoute
  '/frameworks-three-structural-laws': typeof FrameworksThreeStructuralLawsRoute
  '/publications': typeof PublicationsRoute
  '/api/chat': typeof ApiChatRoute
  '/de/about': typeof DeAboutRoute
  '/de/ai-agent': typeof DeAiAgentRoute
  '/de/contact': typeof DeContactRoute
  '/de/frameworks': typeof DeFrameworksRoute
  '/de/insights': typeof DeInsightsRoute
  '/de/publications': typeof DePublicationsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/portfolio/career-intelligence-operating-system': typeof PortfolioCareerIntelligenceOperatingSystemRoute
  '/portfolio/insurance-claims-intelligence-platform': typeof PortfolioInsuranceClaimsIntelligencePlatformRoute
  '/portfolio/knowledge-architecture-operating-system': typeof PortfolioKnowledgeArchitectureOperatingSystemRoute
  '/de': typeof DeIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/de/portfolio/career-intelligence-operating-system': typeof DePortfolioCareerIntelligenceOperatingSystemRoute
  '/de/portfolio/insurance-claims-intelligence-platform': typeof DePortfolioInsuranceClaimsIntelligencePlatformRoute
  '/de/portfolio': typeof DePortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai-agent': typeof AiAgentRoute
  '/aisa': typeof AisaRoute
  '/aisa-v2': typeof AisaV2Route
  '/contact': typeof ContactRoute
  '/de': typeof DeRouteWithChildren
  '/frameworks': typeof FrameworksRoute
  '/frameworks-skaido': typeof FrameworksSkaidoRoute
  '/frameworks-three-structural-laws': typeof FrameworksThreeStructuralLawsRoute
  '/insights': typeof InsightsRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/api/chat': typeof ApiChatRoute
  '/de/about': typeof DeAboutRoute
  '/de/ai-agent': typeof DeAiAgentRoute
  '/de/contact': typeof DeContactRoute
  '/de/frameworks': typeof DeFrameworksRoute
  '/de/insights': typeof DeInsightsRoute
  '/de/portfolio': typeof DePortfolioRouteWithChildren
  '/de/publications': typeof DePublicationsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/portfolio/career-intelligence-operating-system': typeof PortfolioCareerIntelligenceOperatingSystemRoute
  '/portfolio/insurance-claims-intelligence-platform': typeof PortfolioInsuranceClaimsIntelligencePlatformRoute
  '/portfolio/knowledge-architecture-operating-system': typeof PortfolioKnowledgeArchitectureOperatingSystemRoute
  '/de/': typeof DeIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/de/portfolio/career-intelligence-operating-system': typeof DePortfolioCareerIntelligenceOperatingSystemRoute
  '/de/portfolio/insurance-claims-intelligence-platform': typeof DePortfolioInsuranceClaimsIntelligencePlatformRoute
  '/de/portfolio/': typeof DePortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-agent'
    | '/aisa'
    | '/aisa-v2'
    | '/contact'
    | '/de'
    | '/frameworks'
    | '/frameworks-skaido'
    | '/frameworks-three-structural-laws'
    | '/insights'
    | '/portfolio'
    | '/publications'
    | '/api/chat'
    | '/de/about'
    | '/de/ai-agent'
    | '/de/contact'
    | '/de/frameworks'
    | '/de/insights'
    | '/de/portfolio'
    | '/de/publications'
    | '/insights/$slug'
    | '/portfolio/career-intelligence-operating-system'
    | '/portfolio/insurance-claims-intelligence-platform'
    | '/portfolio/knowledge-architecture-operating-system'
    | '/de/'
    | '/insights/'
    | '/portfolio/'
    | '/de/portfolio/career-intelligence-operating-system'
    | '/de/portfolio/insurance-claims-intelligence-platform'
    | '/de/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-agent'
    | '/aisa'
    | '/aisa-v2'
    | '/contact'
    | '/frameworks'
    | '/frameworks-skaido'
    | '/frameworks-three-structural-laws'
    | '/publications'
    | '/api/chat'
    | '/de/about'
    | '/de/ai-agent'
    | '/de/contact'
    | '/de/frameworks'
    | '/de/insights'
    | '/de/publications'
    | '/insights/$slug'
    | '/portfolio/career-intelligence-operating-system'
    | '/portfolio/insurance-claims-intelligence-platform'
    | '/portfolio/knowledge-architecture-operating-system'
    | '/de'
    | '/insights'
    | '/portfolio'
    | '/de/portfolio/career-intelligence-operating-system'
    | '/de/portfolio/insurance-claims-intelligence-platform'
    | '/de/portfolio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-agent'
    | '/aisa'
    | '/aisa-v2'
    | '/contact'
    | '/de'
    | '/frameworks'
    | '/frameworks-skaido'
    | '/frameworks-three-structural-laws'
    | '/insights'
    | '/portfolio'
    | '/publications'
    | '/api/chat'
    | '/de/about'
    | '/de/ai-agent'
    | '/de/contact'
    | '/de/frameworks'
    | '/de/insights'
    | '/de/portfolio'
    | '/de/publications'
    | '/insights/$slug'
    | '/portfolio/career-intelligence-operating-system'
    | '/portfolio/insurance-claims-intelligence-platform'
    | '/portfolio/knowledge-architecture-operating-system'
    | '/de/'
    | '/insights/'
    | '/portfolio/'
    | '/de/portfolio/career-intelligence-operating-system'
    | '/de/portfolio/insurance-claims-intelligence-platform'
    | '/de/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AiAgentRoute: typeof AiAgentRoute
  AisaRoute: typeof AisaRoute
  AisaV2Route: typeof AisaV2Route
  ContactRoute: typeof ContactRoute
  DeRoute: typeof DeRouteWithChildren
  FrameworksRoute: typeof FrameworksRoute
  FrameworksSkaidoRoute: typeof FrameworksSkaidoRoute
  FrameworksThreeStructuralLawsRoute: typeof FrameworksThreeStructuralLawsRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PublicationsRoute: typeof PublicationsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks-three-structural-laws': {
      id: '/frameworks-three-structural-laws'
      path: '/frameworks-three-structural-laws'
      fullPath: '/frameworks-three-structural-laws'
      preLoaderRoute: typeof FrameworksThreeStructuralLawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks-skaido': {
      id: '/frameworks-skaido'
      path: '/frameworks-skaido'
      fullPath: '/frameworks-skaido'
      preLoaderRoute: typeof FrameworksSkaidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks': {
      id: '/frameworks'
      path: '/frameworks'
      fullPath: '/frameworks'
      preLoaderRoute: typeof FrameworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de': {
      id: '/de'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aisa-v2': {
      id: '/aisa-v2'
      path: '/aisa-v2'
      fullPath: '/aisa-v2'
      preLoaderRoute: typeof AisaV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aisa': {
      id: '/aisa'
      path: '/aisa'
      fullPath: '/aisa'
      preLoaderRoute: typeof AisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent': {
      id: '/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/de/': {
      id: '/de/'
      path: '/'
      fullPath: '/de/'
      preLoaderRoute: typeof DeIndexRouteImport
      parentRoute: typeof DeRoute
    }
    '/portfolio/knowledge-architecture-operating-system': {
      id: '/portfolio/knowledge-architecture-operating-system'
      path: '/knowledge-architecture-operating-system'
      fullPath: '/portfolio/knowledge-architecture-operating-system'
      preLoaderRoute: typeof PortfolioKnowledgeArchitectureOperatingSystemRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/insurance-claims-intelligence-platform': {
      id: '/portfolio/insurance-claims-intelligence-platform'
      path: '/insurance-claims-intelligence-platform'
      fullPath: '/portfolio/insurance-claims-intelligence-platform'
      preLoaderRoute: typeof PortfolioInsuranceClaimsIntelligencePlatformRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/career-intelligence-operating-system': {
      id: '/portfolio/career-intelligence-operating-system'
      path: '/career-intelligence-operating-system'
      fullPath: '/portfolio/career-intelligence-operating-system'
      preLoaderRoute: typeof PortfolioCareerIntelligenceOperatingSystemRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/de/publications': {
      id: '/de/publications'
      path: '/publications'
      fullPath: '/de/publications'
      preLoaderRoute: typeof DePublicationsRouteImport
      parentRoute: typeof DeRoute
    }
    '/de/portfolio': {
      id: '/de/portfolio'
      path: '/portfolio'
      fullPath: '/de/portfolio'
      preLoaderRoute: typeof DePortfolioRouteImport
      parentRoute: typeof DeRoute
    }
    '/de/insights': {
      id: '/de/insights'
      path: '/insights'
      fullPath: '/de/insights'
      preLoaderRoute: typeof DeInsightsRouteImport
      parentRoute: typeof DeRoute
    }
    '/de/frameworks': {
      id: '/de/frameworks'
      path: '/frameworks'
      fullPath: '/de/frameworks'
      preLoaderRoute: typeof DeFrameworksRouteImport
      parentRoute: typeof DeRoute
    }
    '/de/contact': {
      id: '/de/contact'
      path: '/contact'
      fullPath: '/de/contact'
      preLoaderRoute: typeof DeContactRouteImport
      parentRoute: typeof DeRoute
    }
    '/de/ai-agent': {
      id: '/de/ai-agent'
      path: '/ai-agent'
      fullPath: '/de/ai-agent'
      preLoaderRoute: typeof DeAiAgentRouteImport
      parentRoute: typeof DeRoute
    }
    '/de/about': {
      id: '/de/about'
      path: '/about'
      fullPath: '/de/about'
      preLoaderRoute: typeof DeAboutRouteImport
      parentRoute: typeof DeRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/portfolio/': {
      id: '/de/portfolio/'
      path: '/'
      fullPath: '/de/portfolio/'
      preLoaderRoute: typeof DePortfolioIndexRouteImport
      parentRoute: typeof DePortfolioRoute
    }
    '/de/portfolio/insurance-claims-intelligence-platform': {
      id: '/de/portfolio/insurance-claims-intelligence-platform'
      path: '/insurance-claims-intelligence-platform'
      fullPath: '/de/portfolio/insurance-claims-intelligence-platform'
      preLoaderRoute: typeof DePortfolioInsuranceClaimsIntelligencePlatformRouteImport
      parentRoute: typeof DePortfolioRoute
    }
    '/de/portfolio/career-intelligence-operating-system': {
      id: '/de/portfolio/career-intelligence-operating-system'
      path: '/career-intelligence-operating-system'
      fullPath: '/de/portfolio/career-intelligence-operating-system'
      preLoaderRoute: typeof DePortfolioCareerIntelligenceOperatingSystemRouteImport
      parentRoute: typeof DePortfolioRoute
    }
  }
}

interface DePortfolioRouteChildren {
  DePortfolioCareerIntelligenceOperatingSystemRoute: typeof DePortfolioCareerIntelligenceOperatingSystemRoute
  DePortfolioInsuranceClaimsIntelligencePlatformRoute: typeof DePortfolioInsuranceClaimsIntelligencePlatformRoute
  DePortfolioIndexRoute: typeof DePortfolioIndexRoute
}

const DePortfolioRouteChildren: DePortfolioRouteChildren = {
  DePortfolioCareerIntelligenceOperatingSystemRoute:
    DePortfolioCareerIntelligenceOperatingSystemRoute,
  DePortfolioInsuranceClaimsIntelligencePlatformRoute:
    DePortfolioInsuranceClaimsIntelligencePlatformRoute,
  DePortfolioIndexRoute: DePortfolioIndexRoute,
}

const DePortfolioRouteWithChildren = DePortfolioRoute._addFileChildren(
  DePortfolioRouteChildren,
)

interface DeRouteChildren {
  DeAboutRoute: typeof DeAboutRoute
  DeAiAgentRoute: typeof DeAiAgentRoute
  DeContactRoute: typeof DeContactRoute
  DeFrameworksRoute: typeof DeFrameworksRoute
  DeInsightsRoute: typeof DeInsightsRoute
  DePortfolioRoute: typeof DePortfolioRouteWithChildren
  DePublicationsRoute: typeof DePublicationsRoute
  DeIndexRoute: typeof DeIndexRoute
}

const DeRouteChildren: DeRouteChildren = {
  DeAboutRoute: DeAboutRoute,
  DeAiAgentRoute: DeAiAgentRoute,
  DeContactRoute: DeContactRoute,
  DeFrameworksRoute: DeFrameworksRoute,
  DeInsightsRoute: DeInsightsRoute,
  DePortfolioRoute: DePortfolioRouteWithChildren,
  DePublicationsRoute: DePublicationsRoute,
  DeIndexRoute: DeIndexRoute,
}

const DeRouteWithChildren = DeRoute._addFileChildren(DeRouteChildren)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface PortfolioRouteChildren {
  PortfolioCareerIntelligenceOperatingSystemRoute: typeof PortfolioCareerIntelligenceOperatingSystemRoute
  PortfolioInsuranceClaimsIntelligencePlatformRoute: typeof PortfolioInsuranceClaimsIntelligencePlatformRoute
  PortfolioKnowledgeArchitectureOperatingSystemRoute: typeof PortfolioKnowledgeArchitectureOperatingSystemRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioCareerIntelligenceOperatingSystemRoute:
    PortfolioCareerIntelligenceOperatingSystemRoute,
  PortfolioInsuranceClaimsIntelligencePlatformRoute:
    PortfolioInsuranceClaimsIntelligencePlatformRoute,
  PortfolioKnowledgeArchitectureOperatingSystemRoute:
    PortfolioKnowledgeArchitectureOperatingSystemRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AiAgentRoute: AiAgentRoute,
  AisaRoute: AisaRoute,
  AisaV2Route: AisaV2Route,
  ContactRoute: ContactRoute,
  DeRoute: DeRouteWithChildren,
  FrameworksRoute: FrameworksRoute,
  FrameworksSkaidoRoute: FrameworksSkaidoRoute,
  FrameworksThreeStructuralLawsRoute: FrameworksThreeStructuralLawsRoute,
  InsightsRoute: InsightsRouteWithChildren,
  PortfolioRoute: PortfolioRouteWithChildren,
  PublicationsRoute: PublicationsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
