/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FrameworksThreeStructuralLawsRouteImport } from './routes/frameworks-three-structural-laws'
import { Route as FrameworksSkaidoRouteImport } from './routes/frameworks-skaido'
import { Route as FrameworksRouteImport } from './routes/frameworks'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AisaV2RouteImport } from './routes/aisa-v2'
import { Route as AisaRouteImport } from './routes/aisa'
import { Route as AiAgentRouteImport } from './routes/ai-agent'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksThreeStructuralLawsRoute =
  FrameworksThreeStructuralLawsRouteImport.update({
    id: '/frameworks-three-structural-laws',
    path: '/frameworks-three-structural-laws',
    getParentRoute: () => rootRouteImport,
  } as any)
const FrameworksSkaidoRoute = FrameworksSkaidoRouteImport.update({
  id: '/frameworks-skaido',
  path: '/frameworks-skaido',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksRoute = FrameworksRouteImport.update({
  id: '/frameworks',
  path: '/frameworks',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AisaV2Route = AisaV2RouteImport.update({
  id: '/aisa-v2',
  path: '/aisa-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const AisaRoute = AisaRouteImport.update({
  id: '/aisa',
  path: '/aisa',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentRoute = AiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-agent': typeof AiAgentRoute
  '/aisa': typeof AisaRoute
  '/aisa-v2': typeof AisaV2Route
  '/contact': typeof ContactRoute
  '/frameworks': typeof FrameworksRoute
  '/frameworks-skaido': typeof FrameworksSkaidoRoute
  '/frameworks-three-structural-laws': typeof FrameworksThreeStructuralLawsRoute
  '/insights': typeof InsightsRoute
  '/portfolio': typeof PortfolioRoute
  '/publications': typeof PublicationsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-agent': typeof AiAgentRoute
  '/aisa': typeof AisaRoute
  '/aisa-v2': typeof AisaV2Route
  '/contact': typeof ContactRoute
  '/frameworks': typeof FrameworksRoute
  '/frameworks-skaido': typeof FrameworksSkaidoRoute
  '/frameworks-three-structural-laws': typeof FrameworksThreeStructuralLawsRoute
  '/insights': typeof InsightsRoute
  '/portfolio': typeof PortfolioRoute
  '/publications': typeof PublicationsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-agent': typeof AiAgentRoute
  '/aisa': typeof AisaRoute
  '/aisa-v2': typeof AisaV2Route
  '/contact': typeof ContactRoute
  '/frameworks': typeof FrameworksRoute
  '/frameworks-skaido': typeof FrameworksSkaidoRoute
  '/frameworks-three-structural-laws': typeof FrameworksThreeStructuralLawsRoute
  '/insights': typeof InsightsRoute
  '/portfolio': typeof PortfolioRoute
  '/publications': typeof PublicationsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-agent'
    | '/aisa'
    | '/aisa-v2'
    | '/contact'
    | '/frameworks'
    | '/frameworks-skaido'
    | '/frameworks-three-structural-laws'
    | '/insights'
    | '/portfolio'
    | '/publications'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-agent'
    | '/aisa'
    | '/aisa-v2'
    | '/contact'
    | '/frameworks'
    | '/frameworks-skaido'
    | '/frameworks-three-structural-laws'
    | '/insights'
    | '/portfolio'
    | '/publications'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-agent'
    | '/aisa'
    | '/aisa-v2'
    | '/contact'
    | '/frameworks'
    | '/frameworks-skaido'
    | '/frameworks-three-structural-laws'
    | '/insights'
    | '/portfolio'
    | '/publications'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAgentRoute: typeof AiAgentRoute
  AisaRoute: typeof AisaRoute
  AisaV2Route: typeof AisaV2Route
  ContactRoute: typeof ContactRoute
  FrameworksRoute: typeof FrameworksRoute
  FrameworksSkaidoRoute: typeof FrameworksSkaidoRoute
  FrameworksThreeStructuralLawsRoute: typeof FrameworksThreeStructuralLawsRoute
  InsightsRoute: typeof InsightsRoute
  PortfolioRoute: typeof PortfolioRoute
  PublicationsRoute: typeof PublicationsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks-three-structural-laws': {
      id: '/frameworks-three-structural-laws'
      path: '/frameworks-three-structural-laws'
      fullPath: '/frameworks-three-structural-laws'
      preLoaderRoute: typeof FrameworksThreeStructuralLawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks-skaido': {
      id: '/frameworks-skaido'
      path: '/frameworks-skaido'
      fullPath: '/frameworks-skaido'
      preLoaderRoute: typeof FrameworksSkaidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks': {
      id: '/frameworks'
      path: '/frameworks'
      fullPath: '/frameworks'
      preLoaderRoute: typeof FrameworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aisa-v2': {
      id: '/aisa-v2'
      path: '/aisa-v2'
      fullPath: '/aisa-v2'
      preLoaderRoute: typeof AisaV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aisa': {
      id: '/aisa'
      path: '/aisa'
      fullPath: '/aisa'
      preLoaderRoute: typeof AisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent': {
      id: '/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAgentRoute: AiAgentRoute,
  AisaRoute: AisaRoute,
  AisaV2Route: AisaV2Route,
  ContactRoute: ContactRoute,
  FrameworksRoute: FrameworksRoute,
  FrameworksSkaidoRoute: FrameworksSkaidoRoute,
  FrameworksThreeStructuralLawsRoute: FrameworksThreeStructuralLawsRoute,
  InsightsRoute: InsightsRoute,
  PortfolioRoute: PortfolioRoute,
  PublicationsRoute: PublicationsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
